### ISSUE TITLE
Any problems including ALL INSTALLED_APPS in public/ default?

### ISSUE THREAD

**Issue by simondrabble** [lorinkoz/django-pgschemas#43]
As a newcomer to multitenancy in general and django-pgschemas in particular, is there any harm in including ALL of my INSTALLED_APPS in both/ either of the public or default tenants? I can see potential performance issues with having every table replicated inside all schemas, but I think this would only affect dynamic tenants? Put another way, how do I decide which apps should be "tenantized" ?

edit: also, how do I decide which apps go in public, and which in default?

**Comment by lorinkoz** [comment]
Hi @simondrabble. Please take a look at this slide and the next two https://lorinkoz.github.io/djcau2020-schemas/#45 (that is, 45, 46 and 47.) In general, you don't place every app on every "schema-level" because you'd be duplicating data that is not going to be used. If we disregard special static tenants for a moment and focus only on public vs "serial dynamic tenants", you want to place on public only what is truly common to all your tenants, and place on the "tenantized schemas" all apps that are the meat of your tenant data.

**Comment by simondrabble** [comment]
Thanks @lorinkoz  for the response. It sounds like public should contain the stuff used to run the app, and default then should contain anything that stores per-tenant data, except for the Client/ Domain data being in public. does that sound like a decent generalization?

**Comment by lorinkoz** [comment]
Yes, sounds right. Let me just give you a readback:

- Client/Domain app should be in public
- Everything else should be in your tenants
- The moment you have something in your tenants that you actually need to be a single source of truth for all tenants, then you move that to public

**Comment by simondrabble** [comment]
That clears things up - thanks! Now I'm off to figure out admins in a multi-tenant world. Thanks again!
